// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1591.Newbot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1591.Newbot.Robot;

/**
 *
 */
public class correctArms extends Command {

    public correctArms() {

        requires(Robot.leftArm);

    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if ( (Robot.rightArm.getPosition() - Robot.leftArm.getPosition()) < -0.005){
    		Robot.leftArm.leftarmDown(0.4);
    	}
    	else if ( (Robot.rightArm.getPosition() - Robot.leftArm.getPosition()) > 0.005){
    		Robot.leftArm.leftarmUp(0.4);
    	}
    	else{
    		Robot.leftArm.leftarmStop();
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if (( (Robot.rightArm.getPosition() - Robot.leftArm.getPosition()) >= -0.005)&&
            	( (Robot.rightArm.getPosition() - Robot.leftArm.getPosition()) <= 0.005)){
            		return true;
            }
            else{
            		return false;
            }
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.leftArm.leftarmStop();
    	Robot.rightArm.rightarmStop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
